AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ExistingIAMUser:
    Type: String
    Default: 'jingting'
    Description: 'Specify the existing IAM user to attach the policy to.'

  ExistingS3Bucket:
    Type: String
    Default: 'bmi-weight-tracker-ionic-demo'
    Description: 'Specify the existing S3 bucket name.'

Resources:
  MyUserPolicy:
    Type: AWS::IAM::UserPolicy
    Properties:
      PolicyName: S3AccessForExistingUser
      UserName: !Ref ExistingIAMUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:ListBucketMultipartUploads
            Resource:
              - !Sub 'arn:aws:s3:::${ExistingS3Bucket}'

          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:DeleteObject
              - s3:AbortMultipartUpload
            Resource:
              - !Sub 'arn:aws:s3:::${ExistingS3Bucket}/*'
